### ISSUE TITLE
'addMetric' of undefined

### ISSUE THREAD

**Issue by rkstar** [versolearning/meteor-intercom#11]
i keep getting this error, but it worked once.  i'm not sure what's up here or why `this.client` is undefined.

```
Uncaught TypeError: Cannot read property 'addMetric' of undefined
```

all the fields in my info object are being set by this func:
```
IntercomSettings.userInfo = function( user, info ){
  if( !user || !user.services ){
    return false
  }
  info.email = user.profile.email
  info.name = user.profile.name
  info.created_at = user.createdAt
}
```

the `user.services` check is for my extended data publication which includes the `createdAt` field.  all the fields in my info object are being set.

any help?

**Comment by crsssl** [comment]
Hi guys, and thanks for the package.
I was wondering where might be the best place to put the ```IntercomSettings.userInfo``` function def.

**Comment by tmeasday** [comment]
Hey @crsssl - we normally put it in `client/main.js` -- a file which loads only on the client, last.

**Comment by tmeasday** [comment]
@rkstar - did you resolve this issue? Sorry about the delay, I missed this one.

**Comment by crsssl** [comment]
@tmeasday All's well until you have to use Intercom's "secured" version. Then we have to get the hashed email or user_id using a method call which is, of course, asynchronous. By the time it returns a value, it's too late -- intercom has already been invoked (with a "no user-hash" error).

**Comment by tmeasday** [comment]
@crsssl right. The function is reactive and if you return `false` it won't do anything. So, if you are using the built in publication, you can do something like

```
if (!user.intercomHash) {
  return false;
}
```

**Comment by crsssl** [comment]
I'm getting the (very) occasional Intercom fail. I think there are situations whereby the user exists but the hash has not been passed down to the client. The POST to Intercom returns ```https://api-ping.intercom.io/vjs/users/ping 403 (Forbidden)```. Looking at the outbound call, the user_hash is missing from the user_data (on POST Form Data).

Possible fix#1: I think there should be another Tracker.autorun() somewhere, to reissue the call to Intercom.

Possible fix#2: Perhaps take the code out of Meteor.startup() and put it somewhere where it can be run on demand or every time.

Again... the problem is intermittent. The best way to try and recreate it:

- Create a project with the Intercom package and Accounts package.
- Add your Intercom credentials to your ```settings.json``` as per instructions.
- Create a user, and log in.
- Navigate to the app page, such that the Intercom button shows up on the lower right corner of the page.
- Navigate to a **whole different page** entirely, i.e. out of your app (say to www.google.com).
- Press the Back button to go back to your app.
- The Intercom button may or may not appear.
- If the Intercom button appears as it should, try again... try navigating back to your app page from elsewhere -- i.e. stay logged in and go back to it in some fashion.

**Comment by tmeasday** [comment]
Hi @crsssl - do you have the if statement? If so it shouldn't send anything with no `intercomHash`...

**Comment by crsssl** [comment]
You're right, I just checked for ```user``` (according to some older documentation I had mistakenly followed), not ```user.intercomHash```. Works very nicely now.
Thanks, Tom.
